### ISSUE TITLE
wepyjs组件支持

### ISSUE THREAD

**Issue by Gcaufy** [kiinlam/wetoast#1]
参考了此repo，做了wepyjs版本的toast组件，使用更方便。
README中已加外链。
https://github.com/wepyjs/wepy-com-toast

**Comment by kiinlam** [comment]
公司的小程序开发安排暂停了，没有继续完善。后续有时间还会再增加点功能。

**Comment by Gcaufy** [comment]
好的，那还时间的话还请多关注关注那个repo
