### ISSUE TITLE
demo运行不起来

### ISSUE THREAD

**Issue by checkme5** [kiinlam/wetoast#2]
demo运行不起来，作者不维护了？
this.wetoast.toast is not a function Page pages/index/index catch error in Page.onTitleToast function
TypeError: this.wetoast.toast is not a function

**Comment by amzfcy** [comment]
+1

**Comment by IMKiller** [comment]
+1

**Comment by kiinlam** [comment]
@checkme5 
@fancyallen 
@IMKiller 
感谢你们的反馈。
问题已经发现了，微信小程序对require函数做了调整，导致在给function的prototype执行赋值时无效，该问题已经处理。
组件使用方法不变。
