### ISSUE TITLE
IOS设备下没有反应，安卓正常

### ISSUE THREAD

**Issue by xudihui** [kiinlam/wetoast#3]
在小程序开发工具中一切正常，当上传为体验版本测试时，发现ios设备都无法正常toast，安卓设备没问题。

**Comment by kiinlam** [comment]
@xudihui  我试了iphone5s IOS10.2系统，没有发现问题。测试的是当前github仓库里的最新代码。
你使用当前github仓库的代码测试的吗？

**Comment by xudihui** [comment]
@kiinlam 我是在iphone6s和iphone5s下都不行，使用的是仓库里最新代码插件方式，小程序里面也包含了一些我自己的业务逻辑，有可能是代码冲突了，谢谢您，可以把你加入我小程序的体验者吗，这样可以发给你直接看看效果了。

**Comment by xudihui** [comment]
@kiinlam 大神，我找到问题了，是我使用的数据缓存方法报错，安卓刚好不报错，删掉对应代码就OK了，谢谢您！
