### ISSUE TITLE
每隔30ms定时去调page.setData()影响小程序性能问题

### ISSUE THREAD

**Issue by Jancat** [kiinlam/wetoast#7]
在**wetoast.js** 里面我看到有个方法每隔30ms会掉用page.setData()，小程序在调试时已经警告了，会影响性能。请问有没有考虑这点，有没有更好的方法？

 ```javascript 
  //显示
  WeToast.prototype.show = function (data) {
    let page = this.__page

    clearTimeout(this.__timeout)

    //display需要先设置为block之后，才能执行动画
    page.setData({
      '__wetoast__.reveal': true
    })

    setTimeout(() => {
      let animation = wx.createAnimation()
      animation.opacity(1).step()
      data.animationData = animation.export()
      data.reveal = true
      page.setData({
        __wetoast__: data
      })
    }, 30)
  ...
}
```

**Comment by kiinlam** [comment]
@Jancat 小程序现已在框架中支持更多的toast功能，推荐使用。
当初写这个小插件时也是为了解决框架本身toast功能的不足，很多开发者也有此诉求，最后微信官方终于做了升级，建议你使用这个新的API。
API地址：https://mp.weixin.qq.com/debug/wxadoc/dev/api/api-react.html#wxshowtoastobject

**Comment by Jancat** [comment]
@kiinlam 目前小程序内置的 `wx.showToast` API 强制使用图标，而且toast框只能是比较大的正方形，不适合那种小提示，在page 底部浮现一行的小toast

**Comment by kiinlam** [comment]
@Jancat 你可以尝试调整30毫秒这个时间间隔，比如改为300毫秒，看看还会不会有提示性能问题，在不超过500毫秒的范围内，用户应该不会有卡顿的感觉。
你也可以改写原型方法`show`，增加传入一个delay参数，将时间间隔改为通过参数来设置。

**Comment by Jancat** [comment]
@kiinlam 在开发时还没发现卡顿，应该没有太大问题
